# This is a basic workflow to help you get started with Actions

name: Runtests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "tensorflow" ]
  pull_request:
    branches: [ "tensorflow" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    branches: [ "tensorflow" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip

      # Install dependencies
      - name: apt install deps
        run: sudo apt install gfortran
        
      # Install pip deps
      - name: pip requirements
        working-directory: fortran-tf-lib/tools
        run: |
          pip install -e ./process_model
          pip install pytest

      # Runs a set of commands using the runners shell
      - name: Run the pytest tests in tools
        working-directory: fortran-tf-lib/tools
        run: |
          pytest tests
